services:
  backend-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    volumes:
      - ./src/:/usr/backend_app/src
      - ./logs/:/usr/backend_app/logs
      - ./.certs/:/usr/backend_app/.certs
    ports:
      - "8080:8080"
    working_dir: /usr/backend_app/
    command: python -m src
    networks:
      - app-network
    depends_on:
      - db-service
    env_file:
      - ./.env
  
  db-service:
    image: postgres:latest
    container_name: db-service
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network
    env_file:
      - ./.env
    ports:
      - 5432:5432

  db-migrations-service:
    image: backend-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-migrations-service
    working_dir: /usr/backend_app/
    volumes:
      - ./src/database/migrations/versions:/usr/backend_app/src/database/migrations/versions
      - ./logs/:/usr/backend_app/logs
      - ./.certs/:/usr/backend_app/.certs
    depends_on:
      - db-service
    networks:
      - app-network
    command: bash -c 'alembic upgrade head'
    env_file:
      - ./.env


volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge