services:
  backend-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    volumes:
      - ./src/:/usr/backend_app/src
    ports:
      - "8080:8080"
    working_dir: /usr/backend_app/
    command: python -m src
    networks:
      - app-network
    depends_on:
      - db-service
  
  db-service:
    image: postgres:latest
    container_name: db-service
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network
    env_file:
      - ./.env
    ports:
      - 5432:5432


volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge