services:
  backend-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    volumes:
      - ./src/:/usr/backend_app/src
    ports:
      - "8080:8080"
    working_dir: /usr/backend_app/
    command: python -m src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge